### ISSUE TITLE
Triggersのコマンド送信ボタンからコマンドが送信できない

### ISSUE THREAD

**Issue by nmxi** [ProjectBLUE-000/RepulserEngine#3]
LTCの受信によってコマンドを送信することは確認できているが

ポン出し用ボタン(Triggers)からだとコマンドが送信されていない気がします.

![image](https://user-images.githubusercontent.com/15684519/118772416-aebf4600-b8be-11eb-819d-c81b6a8001eb.png)

**Comment by kodai100** [comment]
Fixed in #4
